const router=require('express').Router();
const ctrl=require('../controllers/admin.controller');
const {protect}=require('../middleware/auth.middleware');
const {adminOnly}=require('../middleware/admin.middleware');
const multer=require('multer');const path=require('path');
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,'src/uploads/banners'),filename:(req,file,cb)=>cb(null,`banner-${Date.now()}${path.extname(file.originalname)}`)});
const upload=multer({storage,limits:{fileSize:5*1024*1024}});
router.use(protect,adminOnly);
router.get('/dashboard',ctrl.getDashboard);
router.get('/analytics',ctrl.getAnalytics);
router.get('/users',ctrl.getUsers);
router.patch('/users/:id/toggle',ctrl.toggleUser);
router.get('/orders',ctrl.getAllOrders);
router.patch('/orders/:id/status',ctrl.updateOrderStatus);
router.get('/banners',ctrl.getBanners);
router.post('/banners',upload.single('image'),ctrl.createBanner);
router.put('/banners/:id',upload.single('image'),ctrl.updateBanner);
router.delete('/banners/:id',ctrl.deleteBanner);
router.get('/inventory/low-stock',ctrl.getLowStock);
router.post('/inventory/restock',ctrl.restockProduct);
router.get('/settings',ctrl.getSettings);
router.post('/settings',ctrl.updateSetting);
module.exports=router;
