const router=require('express').Router();
const ctrl=require('../controllers/notification.controller');
const {protect}=require('../middleware/auth.middleware');
router.use(protect);
router.get('/',ctrl.getNotifications);
router.patch('/read-all',ctrl.markAllRead);
router.patch('/:id/read',ctrl.markRead);
router.delete('/clear-all',ctrl.clearAll);
router.delete('/:id',ctrl.deleteNotification);
module.exports=router;
